title: Cansoup
permalink: /:year:month:day/:title
url: https://cansoup.github.io/
baseurl:

# variables
name: Cansoup
description: Your description here
google_verification: null
future: true


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false